# Generated by Django 2.1.4 on 2018-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_veicolo', models.IntegerField()),
                ('progressivo', models.IntegerField()),
                ('tipo_veicolo', models.CharField(max_length=1)),
                ('destinazione', models.CharField(max_length=200)),
                ('uso', models.CharField(max_length=200)),
                ('comune_residenza', models.CharField(max_length=200)),
                ('provincia_residenza', models.CharField(max_length=200)),
                ('regione_residenza', models.CharField(max_length=200)),
                ('eta_intestatario', models.IntegerField(blank=True, null=True)),
                ('sesso', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('cilindrata', models.FloatField()),
                ('alimentazione', models.CharField(max_length=200)),
                ('kw', models.IntegerField()),
                ('data_immatricolazione', models.CharField(max_length=200)),
                ('classe_euro', models.IntegerField()),
                ('emissioni_co2', models.IntegerField(blank=True, null=True)),
                ('massa_complessiva', models.IntegerField()),
                ('revisione_in_regola', models.BooleanField(null=True)),
                ('assicurazione_in_regola', models.BooleanField(null=True)),
            ],
        ),
    ]
